name: "Changelog Generator"
description: "Generates and injects changelog into release/hotfix PRs"
author: "Tapbuy"

runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install --upgrade pip requests

        # Appel explicite depuis le dossier du repo appelant (PR)
        python3 -c "import sys; sys.path.insert(0, '${{ github.action_path }}'); import run"
      shell: bash
      working-directory: ${{ github.workspace }}
